### ISSUE TITLE
Fail to derive typeclasses with non-standard functions

### ISSUE THREAD

**Issue by matwojcik** [iRevive/union-derivation#169]
I want to have a type class of this shape:

```scala
//> using scala "3.3.4"
//> using dep "io.github.irevive::union-derivation-core:0.1.0"
//> using options "-Yretain-trees"

import io.github.irevive.union.derivation.{IsUnion, UnionDerivation}

trait MyTypeClass[A]:
  def doSomething(a: A)(b: String): A

object MyTypeClass {

  inline given derivedUnion[A](using IsUnion[A]): MyTypeClass[A] =
    UnionDerivation.derive[MyTypeClass, A]

  given MyTypeClass[String] with {
    def doSomething(a: String)(b: String): String = a

  }

  given MyTypeClass[Int] with {
    def doSomething(a: Int)(b: String): Int = a

  }

}

@main def hello() = {
  println(summon[MyTypeClass[Int | String]].doSomething(1)(""))
}
```

But this fails with:

```
[error] Exception occurred while executing macro expansion.
[error] java.lang.AssertionError: assertion failed: in union (b: String): Int | (b: String): String
[error]         at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[error]         at dotty.tools.dotc.core.Types$.expectValueTypeOrWildcard(Types.scala:3587)
[error]         at dotty.tools.dotc.core.Types$OrType$.apply(Types.scala:3553)
[error]         at dotty.tools.dotc.core.Types$OrType$.balanced(Types.scala:3574)
[error]         at dotty.tools.dotc.core.TypeComparer.orType$$anonfun$1(TypeComparer.scala:2528)
[error]         at dotty.tools.dotc.core.TypeComparer.liftIfHK(TypeComparer.scala:2543)
[error]         at dotty.tools.dotc.core.TypeComparer.orType(TypeComparer.scala:2528)
[error]         at dotty.tools.dotc.core.TypeComparer.mergedLub$1(TypeComparer.scala:2343)
[error]         at dotty.tools.dotc.core.TypeComparer.lub(TypeComparer.scala:2345)
[error]         at dotty.tools.dotc.core.TypeComparer$.lub(TypeComparer.scala:3029)
[error]         at dotty.tools.dotc.core.Types$Type.$bar(Types.scala:1215)
[error]         at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:403)
[error]         at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:16)
[error]         at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:116)
[error]         at dotty.tools.dotc.ast.tpd$.If(tpd.scala:100)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$If$.apply$$anonfun$23(QuotesImpl.scala:875)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:3030)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$If$.apply(QuotesImpl.scala:875)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$If$.apply(QuotesImpl.scala:874)
[error]         at io.github.irevive.union.derivation.UnionDerivation$Macro.mkIfStatement(UnionDerivation.scala:140)
[error]         at io.github.irevive.union.derivation.UnionDerivation$Macro.body(UnionDerivation.scala:104)
[error]         at io.github.irevive.union.derivation.UnionDerivation$Macro.$anonfun$3(UnionDerivation.scala:27)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22$$anonfun$1(QuotesImpl.scala:855)
[error]         at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:302)
[error]         at dotty.tools.dotc.ast.tpd$.Closure(tpd.scala:125)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply$$anonfun$22(QuotesImpl.scala:855)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$.scala$quoted$runtime$impl$QuotesImpl$reflect$$$withDefaultPos(QuotesImpl.scala:3030)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:855)
[error]         at scala.quoted.runtime.impl.QuotesImpl$reflect$Lambda$.apply(QuotesImpl.scala:853)
[error]         at io.github.irevive.union.derivation.UnionDerivation$Macro.deriveImpl(UnionDerivation.scala:27)
[error]         at io.github.irevive.union.derivation.UnionDerivation$.deriveImpl(UnionDerivation.scala:11)
[error] 
[error]   println(summon[MyTypeClass[Int | String]].doSomething(1)(""))
```

I tried to figure out what is the exact reason, and I think that both 
1. type param in the return type of function
2. function with multiple parameters

are not working.

```scala
//> using scala "3.3.4"
//> using dep "io.github.irevive::union-derivation-core:0.1.0"
//> using options "-Yretain-trees"

import io.github.irevive.union.derivation.{IsUnion, UnionDerivation}

trait MyTypeClass[A]:
  def doSomething(a: A): A

object MyTypeClass {

  inline given derivedUnion[A](using IsUnion[A]): MyTypeClass[A] =
    UnionDerivation.derive[MyTypeClass, A] 

  given MyTypeClass[String] with {
    def doSomething(a: String): String = a

  }

  given MyTypeClass[Int] with {
    def doSomething(a: Int): Int = a

  }

}

@main def hello() = {
  println(summon[MyTypeClass[Int | String]].doSomething(1))
}

```

fails with
```
[error] Found:    Int
[error] Required: A
[error]   println(summon[MyTypeClass[Int | String]].doSomething(1))
[error]            
```

and 

```scala
//> using scala "3.3.4"
//> using dep "io.github.irevive::union-derivation-core:0.1.0"
//> using options "-Yretain-trees"

import io.github.irevive.union.derivation.{IsUnion, UnionDerivation}

trait MyTypeClass[A]:
  def doSomething(a: A)(b: String): String

object MyTypeClass {

  inline given derivedUnion[A](using IsUnion[A]): MyTypeClass[A] =
    UnionDerivation.derive[MyTypeClass, A] 

  given MyTypeClass[String] with {
    def doSomething(a: String)(b: String): String = a

  }

  given MyTypeClass[Int] with {
    def doSomething(a: Int)(b: String): String = b

  }

}

@main def hello() = {
  println(summon[MyTypeClass[Int | String]].doSomething(1)(""))
}

```

fails with 

```
Error: Unexpected error when compiling e2e_27aa9d57e7-3296285814: java.lang.AssertionError: assertion failed
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
        at dotty.tools.dotc.typer.Typer.retractDefDef(Typer.scala:2504)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2508)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3092)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3196)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3293)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3339)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1225)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1229)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3124)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.typedFunctionValue(Typer.scala:1694)
        at dotty.tools.dotc.typer.Typer.typedFunction(Typer.scala:1445)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3126)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3382)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1232)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3124)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.adaptNoArgsUnappliedMethod$1(Typer.scala:4021)
        at dotty.tools.dotc.typer.Typer.adaptNoArgs$1(Typer.scala:4164)
        at dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:4393)
        at dotty.tools.dotc.typer.Typer.adapt(Typer.scala:3669)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.$anonfun$14(Typer.scala:1326)
        at dotty.tools.dotc.typer.Applications.harmonic(Applications.scala:2418)
        at dotty.tools.dotc.typer.Applications.harmonic$(Applications.scala:380)
        at dotty.tools.dotc.typer.Typer.harmonic(Typer.scala:116)
        at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:1329)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedIf(Inliner.scala:805)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3125)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3382)
        at dotty.tools.dotc.typer.Typer.$anonfun$57(Typer.scala:2553)
        at dotty.tools.dotc.inlines.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:242)
        at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2553)
        at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:3092)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3196)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:3293)
        at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:3339)
        at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:1225)
        at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:1229)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3124)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3264)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3382)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedSplice(Inliner.scala:840)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3160)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:65)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3121)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3264)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:680)
        at dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:459)
        at dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:164)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.inlineIfNeeded(Inliner.scala:914)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedTypeApply(Inliner.scala:823)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3135)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:65)
        at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3121)
        at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3197)
        at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:918)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3267)
        at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3271)
        at dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:680)
        at dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:459)
        at dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:164)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:95)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1573)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:89)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1614)
        at scala.collection.immutable.List.mapConserve(List.scala:473)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1614)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transformSub(Trees.scala:1618)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1544)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1504)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1510)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1510)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform$$anonfun$1(Trees.scala:1614)
        at scala.collection.immutable.List.mapConserve(List.scala:473)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1614)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1510)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock$$anonfun$1$$anonfun$1(tpd.scala:1235)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1217)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1230)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1235)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1524)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:43)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:91)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:50)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:89)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1230)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1230)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1232)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:58)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:108)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1578)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:89)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1230)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1230)
        at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1232)
        at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1589)
        at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
        at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:97)
        at dotty.tools.dotc.transform.Inlining$$anon$2.transform(Inlining.scala:58)
        at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:18)
        at dotty.tools.dotc.transform.Inlining.run(Inlining.scala:34)
        at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:336)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.immutable.List.foreach(List.scala:334)
        at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:333)
        at dotty.tools.dotc.transform.Inlining.runOn(Inlining.scala:38)
        at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
        at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at dotty.tools.dotc.Run.runPhases$1(Run.scala:308)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:349)
        at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:358)
        at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
        at dotty.tools.dotc.Run.compileUnits(Run.scala:358)
        at dotty.tools.dotc.Run.compileSources(Run.scala:261)
        at dotty.tools.dotc.Run.compile(Run.scala:246)
        at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
        at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
        at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:148)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:73)
        at bloop.tracing.NoopTracer$.trace(BraveTracer.scala:53)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:72)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:181)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by iRevive** [comment]
Hey, thanks for the report!

1) The current implementation is opinionated towards a single argument. For example:
```scala
trait MyTypeClass[A] {
  def doSomething(a: A): String // works
  def doSomething(a: A, b: B): String // doesn't work
}
``` 

This should be fixable on the library's end. 

2) When type param appears in the result position
```scala
trait MyTypeClass[A] {
  def doSomething(a: A): A // doesn't work
}
```

I need to investigate this one.

**Comment by matwojcik** [comment]
> 1. The current implementation is opinionated towards a single argument. For example:
> 
> ```scala
> trait MyTypeClass[A] {
>   def doSomething(a: A): String // works
>   def doSomething(a: A, b: B): String // doesn't work
> }
> ```
> 
> This should be fixable on the library's end.
> 

I tried to workaround it even, by making this a function `def doSomething(a: A): B => A` but it didn't work either.

**Comment by iRevive** [comment]
Ah, I see. 

The type param appears in the result position, and the macro doesn't cast the result type correctly.

**Comment by iRevive** [comment]
The current plan is:
- support multi-param methods - #170
- support poly params in the result position (e.g. `trait MyTypeClass[A] { def doSomething(a: A): A }`)

Curried functions are quite complicated in terms of reconstructions via macro, so I don't promise anything.

**Comment by matwojcik** [comment]
Great, thanks - BTW are extension methods supported as well or do those require a special care?

I mean: 

```scala
trait Showable[A]:
  extension (a: A) def show: String
```

**Comment by iRevive** [comment]
To my surprise it works out of the box:

```scala
trait Showable[A] {
  extension (a: A) def show: String
}

given Showable[Int] = a => a.toString
given Showable[String] = a => a.toString

type UnionType = Int | String
given unionTypeGiven: Showable[UnionType] = UnionDerivation.derive[Showable, UnionType]

assertEquals((42: UnionType).show, "42")
assertEquals(("42": UnionType).show, "42")
```

**Comment by iRevive** [comment]
Hey. I've released the `0.2.0`. 

With minor tweaks I made your example work:
```scala
import io.github.irevive.union.derivation.{IsUnion, UnionDerivation}

trait MyTypeClass[A] {
  def doSomething(a: A): String => A
}

object MyTypeClass {
  inline given derivedUnion[A](using IsUnion[A]): MyTypeClass[A] =
    UnionDerivation.derive[MyTypeClass, A]
    
  given MyTypeClass[String] with {
    def doSomething(a: String): String => String = _ => a
  }
  
  given MyTypeClass[Int] with {
    def doSomething(a: Int): String => Int = _ => a
  }
}

@main def hello() = {
  println(summon[MyTypeClass[Int | String]].doSomething(1)(""))
}
```

I've replaced `def doSomething(a: A)(b: String): A` with `def doSomething(a: A): String => A`.

**Comment by matwojcik** [comment]
Nice, thanks, so far it seems to work fine :)

`def doSomething(a: A)(b: String): A` is off the table? :)

**Comment by iRevive** [comment]
>  is off the table? :)

Yes, for now. But I want to solve this eventually. Here is the task #175.

**Comment by matwojcik** [comment]
@iRevive I am observing some weird behaviour especially when the derivation is executed from e.g. test module, i.e. when I do `MyTypeClass.deriveUnion[String | Int]` I get:

```
[error]    |UnionDerivation cannot derive an instance of trait MyTypeClass for the type `scala.Int | scala.Double | java.lang.String`.
[error]    |Reason: the abstract method without the polymorphic param isn't supported.
[error]    |Hint: check the example below where the instance cannot be derived
[error]    |
[error]    |trait Typeclass[A] {
[error]    |  def magic(a: Int): String
[error]    |  //              ^
[error]    |  // Polymorphic param of type A is missing
[error]    |}
```

But it seems like a non deterministic thing. It also happened when I renamed a file in the same module which used that derivation - then it comes back to compile again when I modify the typeclass file. Like the compilation ordering was important or something? 

It's tough for me to prepare some minimalistic code for this at the moment, but thought maybe you have some obvious hint.

**Comment by iRevive** [comment]
@matwojcik what's the structure of a typeclass there is an issue with?

**Comment by matwojcik** [comment]
The type class is the same as above. Will try to use that in a less complicated project.

**Comment by iRevive** [comment]
You can try to add the `-explain` compiler flag. It may shed some light.

**Comment by majk-p** [comment]
> @iRevive I am observing some weird behaviour especially when the derivation is executed from e.g. test module, i.e. when I do `MyTypeClass.deriveUnion[String | Int]` I get:
> 
> ```
> [error]    |UnionDerivation cannot derive an instance of trait MyTypeClass for the type `scala.Int | scala.Double | java.lang.String`.
> [error]    |Reason: the abstract method without the polymorphic param isn't supported.
> [error]    |Hint: check the example below where the instance cannot be derived
> [error]    |
> [error]    |trait Typeclass[A] {
> [error]    |  def magic(a: Int): String
> [error]    |  //              ^
> [error]    |  // Polymorphic param of type A is missing
> [error]    |}
> ```
> 

I've got the same issue when trying to use 0.2.0 in my code. The same code works fine with 0.1.0. I didn't want to raise a separate issue because all my current attempts to reproduce the issue in a minimize form compile fine :thinking:
